# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='election',
            table='fullvh',
        ),
        migrations.AlterModelTable(
            name='voter',
            table='fullvi',
        ),
    ]
