# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_fullvstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fullvs',
            fields=[
                ('vstat_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_number', models.CharField(blank=True, max_length=50, null=True)),
                ('street_name', models.CharField(blank=True, max_length=50, null=True)),
                ('street_name_2', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('zip_code_4', models.CharField(blank=True, max_length=20, null=True)),
                ('precinct', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('state_rep_district', models.CharField(blank=True, max_length=50, null=True)),
                ('state_senate_district', models.CharField(blank=True, max_length=50, null=True)),
                ('congressional_district', models.CharField(blank=True, max_length=50, null=True)),
                ('ward_council', models.CharField(blank=True, max_length=50, null=True)),
                ('ward_district', models.CharField(blank=True, max_length=50, null=True)),
                ('school_committee_district', models.CharField(blank=True, max_length=50, null=True)),
                ('special_district', models.CharField(blank=True, max_length=50, null=True)),
                ('rvoters', models.IntegerField(blank=True, null=True)),
                ('uvoters', models.IntegerField(blank=True, null=True)),
                ('mvoters', models.IntegerField(blank=True, null=True)),
                ('dvoters', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fullvs',
                'managed': False,
            },
        ),
    ]
